# Generated by Django 5.2.5 on 2025-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_remove_branding_logo_url_branding_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('discord_id', models.CharField(max_length=100)),
                ('members', models.TextField(help_text='Comma-separated list of team members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='branding',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='branding',
            name='primary_color',
            field=models.CharField(default='#c0705a', max_length=7),
        ),
    ]
