# Generated by Django 5.2.5 on 2025-12-10 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_matchregistration_branding_registration_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchregistration',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_registrations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
